# Book settings Learn more at https://jupyterbook.org/customize/config.html

title: High Level Analyses of Confound Regression Leaks 
author: Sami Hamdan

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force 
  timeout: -1

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


# Information about where the book exists on the web
repository:
  url: https://github.com/juaml/ConfoundLeakage  # Online location of your book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
  - sphinx_inline_tabs
